services:

  frontend:
    container_name: turfbuilder_app
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
    restart: unless-stopped
  nats:
    image: nats:2.10
    container_name: nats-turfbuilder
    restart: unless-stopped
    command: [
      "-js",
      "-m", "8222",
      "--store_dir", "/data/jetstream"
    ]
    ports:
      - "4222:4222"   # client connections
      - "8222:8222"   # monitoring
    volumes:
      - nats_data:/data/jetstream
volumes:
  nats_data:
